lib/web/router.ex
defmodule Blog.Web.Router do
  use Blog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Blog.Web do
    pipe_through :browser # Use the default browser stack

    resources "/", PostController do
      resources "/comments", CommentController, only: [:new, :create]
    end
  end
end

lib/web/controllers/comment_controller.ex
defmodule Blog.Web.CommentController do
  use Blog.Web, :controller

  def new(conn, _params) do
    render conn, "new.html", changeset: Blog.changeset(:comment)
  end

  def create(conn, %{"post_id" => post_id, "comment" => comment_params}) do
    result =
      post_id
      |> String.to_integer
      |> Blog.insert_comment(comment_params)

    case result do
      {:ok, _comment} ->
        success(conn, "Comment created!", post_path(conn, :show, post_id))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Oops! There were errors on the form.")
        |> render("new.html", changeset: changeset)
    end
  end
end

lib/web/controllers/post_controller.ex
defmodule Blog.Web.PostController do
  use Blog.Web, :controller

  plug :assign_post when action in [:show, :edit, :update, :delete]

  def index(conn, _params) do

    render conn, "index.html", posts: Blog.list_posts()
  end

  def new(conn, _params) do
    render conn, "new.html", changeset: Blog.changeset(:post)
  end

  def create(conn, %{"post" => post_params}) do
    case Blog.insert_post(post_params) do
      {:ok, post} ->
        success(conn, "Post created!", post_path(conn, :show, post.id))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Oops! There were errors on the form.")
        |> render("new.html", changeset: changeset)
    end
  end

  def show(conn, _params) do
    render conn, "show.html"
  end

  def edit(conn, _params) do
    IO.inspect(conn.assigns.post)
    IO.inspect(Blog.changeset(conn.assigns.post))
    render conn, "edit.html", changeset: Blog.changeset(conn.assigns.post)
  end

  def update(conn, %{"post" => post_params}) do
    case Blog.update_post(conn.assigns.post, post_params) do
      {:ok, post} ->
        success(conn, "Post updated!", post_path(conn, :show, post.id))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Oops! There were errors on the form.")
        |> render("edit.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    case Blog.delete_post(conn.assigns.post) do
      {:ok, _post} ->
        success(conn, "Post deleted!", post_path(conn, :index))
      {:error, _changeset} ->
        error(conn, "Post could not be deleted!", post_path(conn, :index))
    end
  end

  defp assign_post(conn, _opts) do
    case Blog.get_post(conn.params["id"]) do
      %Blog.Post{} = post ->
        assign(conn, :post, post)
      nil ->
        conn
        |> put_flash(:error, "Post not found!")
        |> redirect(to: post_path(conn, :index))
    end
  end
end

lib/web/views/comment_view.ex
defmodule Blog.Web.CommentView do
  use Blog.Web, :view
end

lib/web/views/error_view.ex
defmodule Blog.Web.ErrorView do
  use Blog.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/web/views/layout_view.ex
defmodule Blog.Web.LayoutView do
  use Blog.Web, :view
end

lib/web/views/page_view.ex
defmodule Blog.Web.PageView do
  use Blog.Web, :view
end

lib/web/views/post_view.ex
defmodule Blog.Web.PostView do
  use Blog.Web, :view
end

lib/web/templates/comment/_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= label f, :author %>
  <%= text_input f, :author %>
  <%= error_tag f, :author %>
	<br>
	<br>
  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>
  <br>
  <%= submit "Save Comment" %>
<% end %>

lib/web/templates/comment/new.html.eex
<h1>New Comment</h1>
<%= render "_form.html", Map.merge(assigns, %{action: post_comment_path(@conn, :create, @conn.params["post_id"])}) %>

lib/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Blog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/web/templates/post/_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :author %>
  <%= text_input f, :author %>
  <%= error_tag f, :author %>

  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>

  <%= submit "Save Post" %>
<% end %>

lib/web/templates/post/edit.html.eex
<h1>Edit Post</h1>
<%= render "_form.html", Map.merge(assigns, %{action: post_path(@conn, :update, @changeset.data.id)}) %>

lib/web/templates/post/index.html.eex
<h1>Posts</h1>
<%= link "New Post", to: post_path(@conn, :new) %>

<%= for post <- @posts do %>
  <article>
    <header>
      <h3><%= link post.title, to: post_path(@conn, :show, post.id) %></h3>
      <h4><%= post.author %></h4>
    </header>

    <p><%= post.body %></p>
    <p><%= link "Edit", to: post_path(@conn, :edit, post.id) %></p>
  </article>
<% end %>

lib/web/templates/post/new.html.eex
<h1>New Post</h1>
<%= render "_form.html", Map.merge(assigns, %{action: post_path(@conn, :create)}) %>

lib/web/templates/post/show.html.eex
<article>
  <header>
    <h3><%= @post.title %></h3>
    <h4><%= @post.author %></h4>
    <%= link "Back to Posts", to: post_path(@conn, :index) %>
  </header>

  <p><%= @post.body %></p>
  <p><%= link "Edit", to: post_path(@conn, :edit, @post.id) %></p>

  <section>
    <h3>Comments</h3>
    <%= link "New Comment", to: post_comment_path(@conn, :new, @post.id) %>
    <%= for comment <- @post.comments do %>
      <p><%= comment.author %></p>
      <p><%= comment.body %></p>
    <% end %>
  </section>
</article>